USE MODULE14

--CREATING THE TRIGGER WHO RESTRICT USER TO CREATE TABLE
CREATE TRIGGER TABLE_CREATE_RESTRICTION 
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
ROLLBACK
PRINT 'NOT ALLOW TO CREATE TABLE'
END

--NOT ALLOW TO CRAETE HELLO TABLE 
CREATE TABLE HELLO(
ID INT
)

--CREATING THE TRIGGER FOR NOT DELETE RECORDS FROM TABLE
ALTER TRIGGER TABLE_CREATE_RESTRICTION 
ON EMPLOYEE_TEST
FOR DELETE
AS
BEGIN
ROLLBACK
PRINT 'NOT ALLOW TO DELETE RECORDS FROM TABLE'
END

--NOT ALLOWED TO DELETE THE RECORD
DELETE FROM Employee_Test WHERE Emp_ID = 1


CREATE TRIGGER INSERT_AUDIT_TEST
ON EMPLOYEE_TEST
FOR INSERT
AS
BEGIN
DECLARE @ID INT
DECLARE @NAME VARCHAR(100)
DECLARE @SAL DECIMAL(10,2)
SELECT @ID = EMP_ID FROM INSERTED
SELECT @NAME = EMP_NAME FROM INSERTED
SELECT @SAL = EMP_SAL FROM INSERTED


INSERT INTO Employee_Test_Audit(Emp_ID,Emp_name,Emp_Sal)
VALUES(@ID,@NAME,@SAL)

END

INSERT INTO Employee_Test VALUES(21,'JHON',30000)


