USE MODULE15

--create table
CREATE TABLE ACCOUNT1
(
ID INT PRIMARY KEY,
NAME VARCHAR(100),
BALANCE BIGINT
)

--inserted values
INSERT INTO ACCOUNT1 VALUES(1,'TANMAY',50000)
INSERT INTO ACCOUNT1 VALUES(2,'VISHWA',60000)
INSERT INTO ACCOUNT1 VALUES(3,'VIR',80000)
INSERT INTO ACCOUNT1 VALUES(4,'OM',30000)


SELECT * FROM ACCOUNT1

--set isolation level & create transaction as T1
SET TRANSACTION ISOLATION LEVEL   
READ UNCOMMITTED
BEGIN TRAN T1
DECLARE @BALANCE BIGINT
SET @BALANCE = 14000
INSERT INTO ACCOUNT1 VALUES(5,'ABC',@BALANCE)
IF(@BALANCE > 15000)
BEGIN
 PRINT 'DEPOSIT MORE THAN 15000 AT ONE MOVEMENT IS NOT ALLOWED'
 ROLLBACK TRAN T1
END
ELSE
BEGIN
PRINT 'DATA INSERTED'
COMMIT TRAN T1
END 
